# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  host: localhost
  port: 8080

development:
  <<: *default
  database: c9
  username: <%=ENV['C9_USER']%>

test:
  <<: *default
  database: c9_test
  username: <%=ENV['C9_USER']%>

production:
  <<: *default
